workspace(name = "android-multimodule")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

RULES_JAVA_VERSION = "4.0.0"
RULES_JAVA_SHA = "34b41ec683e67253043ab1a3d1e8b7c61e4e8edefbcad485381328c934d072fe"

http_archive(
    name = "rules_java",
    sha256 = RULES_JAVA_SHA,
    url = "https://github.com/bazelbuild/rules_java/releases/download/{v}/rules_java-{v}.tar.gz".format(v = RULES_JAVA_VERSION),
)

load(
    "@rules_java//java:repositories.bzl",
    "rules_java_dependencies",
    "rules_java_toolchains",
)

rules_java_dependencies()

rules_java_toolchains()

DAGGER_TAG = "2.36"
DAGGER_SHA = "1e6d5c64d336af2e14c089124bf2bd9d449010db02534ce820abc6a7f0429c86"

http_archive(
    name = "dagger",
    sha256 = DAGGER_SHA,
    strip_prefix = "dagger-dagger-%s" % DAGGER_TAG,
    urls = ["https://github.com/google/dagger/archive/dagger-%s.zip" % DAGGER_TAG],
)

load(
    "@dagger//:workspace_defs.bzl",
    "DAGGER_ARTIFACTS",
    "DAGGER_REPOSITORIES",
)

RULES_JVM_EXTERNAL_VERSION = "4.1"
RULES_JVM_EXTERNAL_SHA = "f36441aa876c4f6427bfb2d1f2d723b48e9d930b62662bf723ddfb8fc80f0140"

http_archive(
    name = "rules_jvm_external",
    sha256 = RULES_JVM_EXTERNAL_SHA,
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_VERSION,
    urls = ["https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_VERSION],
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = DAGGER_ARTIFACTS + [
        "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.1",
        "androidx.core:core-ktx:1.6.0",
        "androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.1",
        "androidx.lifecycle:lifecycle-runtime-ktx:2.4.0-alpha02",
        "androidx.fragment:fragment-ktx:1.4.0-alpha04",
        "androidx.appcompat:appcompat:1.3.0",
        "com.google.android.material:material:1.4.0",
        "androidx.constraintlayout:constraintlayout:2.0.4",
        "io.coil-kt:coil:1.3.1",
    ],
    repositories = DAGGER_REPOSITORIES + [
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ],
    override_targets = {"org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm": "@//third_party:kotlinx_coroutines_core_jvm"},
)

maven_install(
    name = "maven_secondary",
    artifacts = ["org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.5.1"],
    repositories = ["https://repo1.maven.org/maven2"],
)

RULES_ANDROID_VERSION = "0.1.1"
RULES_ANDROID_SHA = "cd06d15dd8bb59926e4d65f9003bfc20f9da4b2519985c27e190cddc8b7a7806"

http_archive(
    name = "rules_android",
    sha256 = RULES_ANDROID_SHA,
    strip_prefix = "rules_android-%s" % RULES_ANDROID_VERSION,
    urls = ["https://github.com/bazelbuild/rules_android/archive/v%s.zip" % RULES_ANDROID_VERSION],
)

load("@rules_android//android:rules.bzl", "android_sdk_repository")

android_sdk_repository(
    name = "androidsdk",
    api_level = 29,
    build_tools_version = "29.0.3",
)

RULES_KOTLIN_VERSION = "v1.5.0-beta-2"
RULES_KOTLIN_SHA = "eeae65f973b70896e474c57aa7681e444d7a5446d9ec0a59bb88c59fc263ff62"

http_archive(
    name = "io_bazel_rules_kotlin",
    sha256 = RULES_KOTLIN_SHA,
    type = "tar.gz",
    urls = ["https://github.com/bazelbuild/rules_kotlin/releases/download/%s/rules_kotlin_release.tgz" % RULES_KOTLIN_VERSION],
)

load(
    "@io_bazel_rules_kotlin//kotlin:kotlin.bzl",
    "kotlin_repositories",
    "kt_register_toolchains",
)

kotlin_repositories()

kt_register_toolchains()