workspace(name = "sample")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")


COMPOSE_VERSION = "1.0.0-beta08"
KOTLIN_COMPILER_VERSION = "1.5.10"


# ===== dagger =====

DAGGER_TAG = "2.36"
DAGGER_SHA = "1e6d5c64d336af2e14c089124bf2bd9d449010db02534ce820abc6a7f0429c86"

#DAGGER_TAG = "2.28.1"
#DAGGER_SHA = "9e69ab2f9a47e0f74e71fe49098bea908c528aa02fa0c5995334447b310d0cdd"

http_archive(
    name = "dagger",
    strip_prefix = "dagger-dagger-%s" % DAGGER_TAG,
    sha256 = DAGGER_SHA,
    urls = ["https://github.com/google/dagger/archive/dagger-%s.zip" % DAGGER_TAG],
)

load("@dagger//:workspace_defs.bzl", "DAGGER_ARTIFACTS", "DAGGER_REPOSITORIES")


# ===== jvm external =====

RULES_JVM_EXTERNAL_VERSION = "4.1"

RULES_JVM_EXTERNAL_SHA = "f36441aa876c4f6427bfb2d1f2d723b48e9d930b62662bf723ddfb8fc80f0140"

http_archive(
    name = "rules_jvm_external",
    sha256 = RULES_JVM_EXTERNAL_SHA,
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_VERSION,
    urls = [
        "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_VERSION,
    ],
)

load("@rules_jvm_external//:defs.bzl", "maven_install")
load("@rules_jvm_external//:specs.bzl", "maven")

COMPOSE_ACTIVITY_VERSION = "1.3.0-alpha08"
COMPOSE_NAVIGATION_VERSION = "2.4.0-alpha01"
COMPOSE_VIEW_MODEL_VERSION = "1.0.0-alpha05"
COMPOSE_PAGING_VERSION = "1.0.0-alpha09"
COMPOSE_COIL_VERSION = "0.10.0"

ROOM_VERSION = "2.3.0"

maven_install(
    artifacts = DAGGER_ARTIFACTS + [
        "org.jetbrains.kotlin:kotlin-stdlib:%s" % KOTLIN_COMPILER_VERSION,

        "androidx.core:core-ktx:1.5.0",
        "androidx.appcompat:appcompat:1.3.0",
        "com.google.android.material:material:1.3.0",
        "androidx.palette:palette-ktx:1.0.0",

        "androidx.compose.ui:ui:%s" % COMPOSE_VERSION,
        "androidx.compose.ui:ui-tooling:%s" % COMPOSE_VERSION,
        "androidx.compose.compiler:compiler:%s" % COMPOSE_VERSION,
        "androidx.compose.runtime:runtime:%s" % COMPOSE_VERSION,
        "androidx.compose.material:material:%s" % COMPOSE_VERSION,
        "androidx.activity:activity-compose:%s" % COMPOSE_ACTIVITY_VERSION,
        "androidx.navigation:navigation-compose:%s" % COMPOSE_NAVIGATION_VERSION,
        "androidx.paging:paging-compose:%s" % COMPOSE_PAGING_VERSION,
        "com.google.accompanist:accompanist-coil:%s" % COMPOSE_COIL_VERSION,
        "androidx.lifecycle:lifecycle-viewmodel-compose:%s" % COMPOSE_VIEW_MODEL_VERSION,

        "androidx.paging:paging-runtime-ktx:3.0.0",

        "com.squareup.retrofit2:retrofit:2.9.0",
        "com.squareup.retrofit2:converter-moshi:2.9.0",
        "com.squareup.okhttp3:logging-interceptor:4.2.1",
        "com.squareup.moshi:moshi-kotlin:1.12.0",

        "androidx.room:room-runtime:%s" % ROOM_VERSION,
        "androidx.room:room-compiler:%s" % ROOM_VERSION,
        "androidx.room:room-ktx:%s" % ROOM_VERSION,

        "androidx.lifecycle:lifecycle-runtime-ktx:2.3.1",
        "androidx.lifecycle:lifecycle-livedata-ktx:2.3.1",

        "com.google.guava:guava:28.1-android",
    ],
    excluded_artifacts = [
        # kotlin_rules has bug while desugaring kotlin-reflect artifact.
        # This case appeared when including moshi-kotlin to target deps
        "org.jetbrains.kotlin:kotlin-reflect",
    ],
    override_targets = {
        "org.jetbrains.kotlin:kotlin-stdlib": "@com_github_jetbrains_kotlin//:kotlin-stdlib",
        "org.jetbrains.kotlin:kotlin-stdlib-jdk7": "@com_github_jetbrains_kotlin//:kotlin-stdlib-jdk7",
        "org.jetbrains.kotlin:kotlin-stdlib-jdk8": "@com_github_jetbrains_kotlin//:kotlin-stdlib-jdk8",
    },
    repositories = DAGGER_REPOSITORIES + [
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ],
)


# ===== android =====


_RULES_ANDROID_VERSION = "0.1.1"

_RULES_ANDROID_SHA = "cd06d15dd8bb59926e4d65f9003bfc20f9da4b2519985c27e190cddc8b7a7806"

http_archive(
    name = "build_bazel_rules_android",
    sha256 = _RULES_ANDROID_SHA,
    strip_prefix = "rules_android-{}".format(_RULES_ANDROID_VERSION),
    urls = [
        "https://github.com/bazelbuild/rules_android/archive/v{}.zip".format(_RULES_ANDROID_VERSION),
    ],
)

load("@build_bazel_rules_android//android:rules.bzl", "android_sdk_repository")

http_archive(
    name = "rules_android",
    urls = ["https://github.com/bazelbuild/rules_android/archive/v0.1.1.zip"],
    sha256 = "cd06d15dd8bb59926e4d65f9003bfc20f9da4b2519985c27e190cddc8b7a7806",
    strip_prefix = "rules_android-0.1.1",
)

android_sdk_repository(
    name = "androidsdk",
    api_level = 29,
    build_tools_version = "29.0.3",
)

# ===== kotlin =====

RULES_KOTLIN_VERSION = "v1.5.0-alpha-3"
RULES_KOTLIN_SHA = "eeae65f973b70896e474c57aa7681e444d7a5446d9ec0a59bb88c59fc263ff62"

#http_archive(
#    name = "io_bazel_rules_kotlin",
#    sha256 = RULES_KOTLIN_SHA,
#    type = "tar.gz",
#    urls = ["https://github.com/bazelbuild/rules_kotlin/releases/download/%s/rules_kotlin_release.tgz" % RULES_KOTLIN_VERSION],
#)
local_repository(
    name = "io_bazel_rules_kotlin",
    path = "../../../../Sources/rules_kotlin_release_1_5"
)

load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kotlin_repositories")

RULES_KOTLIN_COMPILER_RELEASE = {
    "urls": [
        "https://github.com/JetBrains/kotlin/releases/download/v{v}/kotlin-compiler-{v}.zip".format(v = KOTLIN_COMPILER_VERSION),
    ],
    "sha256": "2f8de1d73b816354055ff6a4b974b711c11ad55a68b948ed30b38155706b3c4e",
}

kotlin_repositories(
    compiler_release = RULES_KOTLIN_COMPILER_RELEASE,
)

register_toolchains("//:kotlin_toolchain")