name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Run tests
        run: |
          ./gradlew airin-core:build
          ./gradlew airin-gradle-plugin:build
          ./gradlew airin-gradle-android:build


